services:
  api:
    build:
      context: .
      dockerfile: src/XgpLib.SyncService.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__XgpLibPostgres=Host=postgres;Port=5432;Database=xgplib;Username=ademir;Password=1234@4321
      - RabbitMq__HostName=rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - xgplib-network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ademir
      POSTGRES_PASSWORD: 1234@4321
      POSTGRES_DB: xgplib
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - xgplib-network

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: ademir
      RABBITMQ_DEFAULT_PASS: 1234@4321
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - xgplib-network

volumes:
  postgres-data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  xgplib-network:
    driver: bridge
