services:
  api:
    build:
      context: .
      dockerfile: src/XgpLib.SyncService.Api/Dockerfile
    ports:
      - "3080:80"
      - "3443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=-\0pw-
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__XgpLibPostgres=Host=postgres;Port=5432;Database=xgplib;Username=;Password=
      - RabbitMq__HostName=rabbitmq
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - xgplib-network

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ademir
      POSTGRES_PASSWORD:
      POSTGRES_DB: xgplib
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - xgplib-network

  rabbitmq:
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: ademir
      RABBITMQ_DEFAULT_PASS:
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - xgplib-network

volumes:
  postgres-data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  xgplib-network:
    driver: bridge
